version: '2'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server
    ports:
      - '6379:6379'
  website:
    build: .
    command: supervisord -n
    environment:
      ENV: 'dev'
      URL: 'http://ubuntu.oreillyauto.com'
      SERVER_NAME: 'ubuntu.oreillyauto.com'
      SQLALCHEMY_DATABASE_URI: "mysql://root:bacon@suite_db_1/dev"
      REDIS_HOST: redis
    volumes:
      - '.:/src'
    ports:
      - '80:80'
    links:
      - db
      - redis
    hostname: suite
  db:
    hostname: mysqlserver
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: bacon
        MYSQL_DATABASE: dev
