"""empty message

Revision ID: 3b63f4168ce7
Revises: 3c1542929556
Create Date: 2019-05-07 20:04:13.950116

"""

# revision identifiers, used by Alembic.
revision = '3b63f4168ce7'
down_revision = '3c1542929556'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
